"""Integration tests for report read endpoints.

Reports are generated by the scheduler, not on request — there is no
generation endpoint. A report row is inserted directly to test retrieval.
"""

from datetime import date


def _insert_report(db, user_id: int, period: str = "week",
                   period_start: str = "2026-01-05", period_end: str = "2026-01-11"):
    db.execute(
        """INSERT INTO report
           (user_id, period, period_start, period_end, avg_productivity,
            active_days, created_at, final_report)
           VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
        (user_id, period, period_start, period_end, 4.5, 3, date.today(),
         '{"summary": "great week"}'),
    )


def test_reports_require_auth(client):
    assert client.get("/reports/list?period=week").status_code in (401, 403)


def test_generate_endpoint_is_gone(client, make_user):
    """The manual generation endpoint was removed; only the scheduler generates."""
    user = make_user()
    res = client.post(
        "/reports/generate",
        json={"period": "week", "period_start": "2026-01-05", "period_end": "2026-01-11"},
        headers=user["headers"],
    )
    assert res.status_code in (404, 405)


def test_list_reports_empty(client, make_user):
    user = make_user()
    res = client.get("/reports/list?period=week", headers=user["headers"])
    assert res.status_code == 200
    assert res.json() == []


def test_get_report_returns_null_when_missing(client, make_user):
    user = make_user()
    res = client.get("/reports?period=week&period_start=2026-01-05", headers=user["headers"])
    assert res.status_code == 200
    assert res.json() is None


def test_list_and_get_stored_report(client, db, make_user):
    user = make_user()
    _insert_report(db, user["user_id"])

    listed = client.get("/reports/list?period=week", headers=user["headers"]).json()
    assert len(listed) == 1
    assert listed[0]["final_report"] == {"summary": "great week"}

    one = client.get(
        "/reports?period=week&period_start=2026-01-05", headers=user["headers"]
    ).json()
    assert one["avg_productivity"] == 4.5


def test_reports_scoped_to_user(client, db, make_user):
    alice = make_user("alice@example.com")
    bob = make_user("bob@example.com")
    _insert_report(db, alice["user_id"])

    assert client.get("/reports/list?period=week", headers=bob["headers"]).json() == []
