"""Email delivery via Resend.

Single responsibility: send a one-time login code to the user's email.
All Resend configuration is read from ``AppSettings``.

Resend docs: https://resend.com/docs/send-with-python
Free tier:   3 000 emails / month, no credit card required.
"""

from src.core.settings import get_settings


async def send_login_code(email: str, code: str) -> None:
    """Send a 6-digit login code to *email* via Resend.

    Constructs a simple plain-text (and minimal HTML) email containing
    the code and a 10-minute expiry notice.

    Args:
        email: Recipient address.
        code:  6-digit one-time code generated by the auth route.

    Raises:
        RuntimeError: If the Resend API returns a non-2xx response.
    """
    raise NotImplementedError
